import { ContactForm } from "@/components/contact-form";
import { Cursor } from "@/components/cursor";
import { EquipmentCanvas } from "@/components/equipment-canvas";
import { Hero } from "@/components/hero";
import { Navigation } from "@/components/navigation";
import { Reveal } from "@/components/reveal";
import { SmoothScroll } from "@/components/smooth-scroll";
import type { CSSProperties } from "react";

const services=["Brand Strategy","Advertising & Campaigns","Content Production","Digital & Social","Creator Management","Events & Experiences","Film, OTT & Music","IP, Rights & Distribution","Platforms & Technology"];
const work=["Aurelia / Brand Platform","Still Moving / Integrated Campaign","On Frequency / Entertainment","Elysian / Digital Experience"];
const serviceVisuals=["film-automotive.png","service-brand.png","film-music.png","service-documentary.png","film-virtual.png","service-drone.png","service-photography.png","service-vfx.png","service-motion.png"];
const workVisuals=["film-automotive.png","film-music.png","film-virtual.png","service-motion.png"];

export default function Home(){const base=process.env.NEXT_PUBLIC_BASE_PATH??"";const sharedStyle={"--hero-image":`url(${base}/cineverse-hero.png)`} as CSSProperties;return <><SmoothScroll/><Cursor/><Navigation/><main style={sharedStyle}><Hero/>
  <section id="studio" className="about wrap"><Reveal><p className="eyebrow">01 / Narayani Studios LLP</p><h2>Ideas with the power to <em>move people.</em></h2></Reveal><Reveal className="about-side"><p>We are an integrated creative business for a world where a brand can become a story, a film, an event, a platform or a lasting cultural property. Strategy, content, technology and entertainment—working as one.</p><div className="stats"><span><b>360°</b>creative services</span><span><b>India +</b>global reach</span><span><b>IP-led</b>thinking</span><span><b>One</b>integrated partner</span></div></Reveal></section>
  <section id="services" className="services wrap"><Reveal><p className="eyebrow">02 / Capabilities</p><h2>Everything a living<br/>brand needs to <em>grow.</em></h2></Reveal><div className="service-grid">{services.map((service,index)=><Reveal key={service}><article className={`service-card service-${index+1}`} style={{"--card-image":`url(${base}/${serviceVisuals[index]})`} as CSSProperties}><span>0{index+1}</span><h3>{service}</h3><i>↗</i></article></Reveal>)}</div></section>
  <section id="work" className="work wrap"><Reveal><p className="eyebrow">03 / Selected Work</p><h2>Stories made to<br/>travel <em>further.</em></h2></Reveal><div className="film-grid">{work.map((item,index)=><Reveal key={item} className={`film film-${index+1}`}><button aria-label={`View ${item}`} style={{"--film-image":`url(${base}/${workVisuals[index]})`} as CSSProperties}><div><small>Selected project / 0{index+1}</small><h3>{item}</h3><span>Explore the work ↗</span></div></button></Reveal>)}</div></section>
  <section className="bts"><div className="bts-image"/><Reveal className="bts-copy"><p className="eyebrow">04 / Content Studio</p><h2>From the first thought to the <em>final release.</em></h2><p>We develop concepts, build campaigns, produce content and deliver across social, digital, print, broadcast, live and emerging platforms.</p></Reveal></section>
  <section id="media" className="equipment wrap"><Reveal><p className="eyebrow">05 / Media, IP & Technology</p><h2>Build it. Own it.<br/><em>Take it everywhere.</em></h2></Reveal><EquipmentCanvas/><Reveal className="equipment-copy"><p>We conceive and commercialise films, web series, podcasts, music, branded entertainment, digital communities, websites, applications and intellectual property.</p><a href="#contact" className="text-link">Discuss a media or IP opportunity ↗</a></Reveal></section>
  <section className="workflow wrap"><Reveal><p className="eyebrow">06 / How we work</p><h2>One clear path<br/>from ambition to <em>impact.</em></h2></Reveal><ol>{["Discover","Strategise","Create","Produce","Launch","Grow","Evolve"].map((item,index)=><Reveal key={item}><li><small>0{index+1}</small><b>{item}</b><i>↓</i></li></Reveal>)}</ol></section>
  <section className="testimonials"><div className="marquee"><span>MAKE CULTURE MOVE — MAKE CULTURE MOVE — MAKE CULTURE MOVE — </span><span>MAKE CULTURE MOVE — MAKE CULTURE MOVE — MAKE CULTURE MOVE — </span></div><div className="testimonial wrap"><Reveal><p className="eyebrow">07 / Our belief</p><blockquote>“The strongest brands do not interrupt culture. They <em>help create it.</em>”</blockquote><p>Narayani Studios LLP / Creative Business</p></Reveal></div></section>
  <section className="awards wrap"><Reveal><p className="eyebrow">08 / Industries & Formats</p><div className="award-list"><span>Brands & Startups</span><span>Media & Entertainment</span><span>Creators & Talent</span><span>Live & Digital Experiences</span></div></Reveal></section>
  <section id="contact" className="contact wrap"><Reveal><p className="eyebrow">09 / Start a conversation</p><h2>Let’s make<br/><em>what’s next.</em></h2><p>Tell us the opportunity. We’ll bring the team, the ideas and the momentum.</p></Reveal><Reveal><ContactForm/></Reveal></section>
  </main><footer className="wrap"><a className="wordmark" href="#top">NARAYANI <i>STUDIOS LLP</i></a><span>India · Global</span><span>© 2026</span></footer></>}
