import { notFound } from "next/navigation";
import Link from "next/link";

const pages={
  productions:{eyebrow:"CineVerse / Production",title:"Execution for every <em>ambition.</em>",copy:"From creative strategy and planning to shoots, content, campaigns and final delivery, we bring the right expertise to every stage of the work.",image:"/film-automotive.png",items:["Campaign production","Content & brand experiences","Music, photography & live","Integrated delivery"]},
  portfolio:{eyebrow:"CineVerse / Portfolio",title:"A record of worlds <em>made real.</em>",copy:"A selected portfolio spanning brand storytelling, culture, launch moments and moving image.",image:"/film-virtual.png",items:["Narrative films","Brand platforms","Social-first series","Live experiences"]},
  talent:{eyebrow:"CineVerse / Talent",title:"The people behind the <em>possibility.</em>",copy:"A carefully assembled network of directors, photographers, producers, artists and emerging voices.",image:"/service-photography.png",items:["Directors & producers","Photographers","Music & sound","Creators & collaborators"]},
  team:{eyebrow:"CineVerse / Team",title:"A studio of sharp <em>point of view.</em>",copy:"A senior, multidisciplinary team that pairs imagination with operational excellence.",image:"/service-documentary.png",items:["Creative direction","Production leadership","Brand strategy","Digital & experience"]},
  "media-ip":{eyebrow:"CineVerse / Media & IP",title:"Make it. Own it. <em>Take it further.</em>",copy:"We develop media properties, original formats and digital ecosystems built to grow beyond a single release.",image:"/service-vfx.png",items:["Original IP development","Platform concepts","Distribution strategy","Rights & partnerships"]},
  insights:{eyebrow:"CineVerse / Insights",title:"Notes from inside the <em>frame.</em>",copy:"A closer look at the thinking, process and people behind culture-moving work.",image:"/service-motion.png",items:["Creative process","Production journals","Culture & commentary","Studio news"]},
} as const;
export function generateStaticParams(){return Object.keys(pages).map(studio=>({studio}))}
export default async function StudioPage({params}:{params:Promise<{studio:string}>}){const {studio}=await params;const page=pages[studio as keyof typeof pages];if(!page)notFound();return <main className="aurora-page"><section className="aurora-page-hero" style={{backgroundImage:`linear-gradient(90deg,#07080df2 8%,#07080d69 70%),url(${page.image})`}}><div className="wrap"><p className="eyebrow">{page.eyebrow}</p><h1 dangerouslySetInnerHTML={{__html:page.title}}/><p>{page.copy}</p></div></section><section className="aurora-index wrap">{page.items.map((item,index)=><article key={item}><span>0{index+1}</span><h2>{item}</h2><i>↗</i></article>)}</section><section className="aurora-cta wrap"><p className="eyebrow">Build with us</p><h2>Bring the next <em>chapter.</em></h2><Link className="button aurora-button" href="/contact">Start a conversation <span>↗</span></Link></section></main>}
